apiVersion: v1
kind: Service
metadata:
  name: calljsoncode-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: calljsoncode 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
